data_path = '/data/aswo/data/insitu_python/'
movie_path = '/perm/aswo/ops/elevo/movies/'
frames_path = '/perm/aswo/ops/elevo/frames/'
results_path = '/perm/aswo/ops/elevo/output/'
arrival_path = '/perm/aswo/ops/elevo/arrival/'
overview_path = '/data/aswo/eweiler/overview/'
overview_frames_path = '/data/aswo/eweiler/overview/frames/'
overview_movie_path = '/data/aswo/eweiler/overview/movie/'